### ISSUE TITLE
Modify collection name ?

### ISSUE THREAD

**Issue by MatthieuHPP** [lklepner/socket.io-adapter-mongo#10]
Hello,

Many thanks for this nice module, I have tested with socket.io@2.
I do have a basic question : how can I modify the name of the collection that is created ?

Matthieu

**Comment by appsolutegeek** [comment]
Yes, I would also like to know this. I thought it might be in the options but it appears it is not.

**Comment by lklepner** [comment]
I took over administration of this module last spring and until today hadn't tried to customize the collection name.

It looks like the original author intended the options.key value for this purpose -
https://github.com/lklepner/socket.io-adapter-mongo#adapteropts

I just tested it and can confirm it writes to the specified collection name.  Unfortunately it also throws a MongoDB warning since the options object is also being passed with the key value. 

I just pushed a fix that corrects this to the fixKey branch

**Comment by lklepner** [comment]
Fix tested, merged and released to npm as v2.0.3
