### ISSUE TITLE
It doesn't work with socket.io 2.x.x

### ISSUE THREAD

**Issue by ctretyak** [lklepner/socket.io-adapter-mongo#2]
There is an error "TypeError: this.adapter.addAll is not a function"

**Comment by lklepner** [comment]
I haven't delved into socket.io 2.x and don't foresee doing so in the coming weeks/months.

If you would like to take this on I would gladly accept a PR

**Comment by amcdnl** [comment]
I think the socket.io-adapter just needs to be bumped to support this. https://github.com/socketio/socket.io-adapter

**Comment by lklepner** [comment]
This is a breaking change since socket.io-adapter 1.0.x requires socket.io v2 or later. 

Would one of you like to prepare a socket.io-adapter-mongo v2.0.0 PR? 

I wonder if socket.io-mongodb-emitter will need to be updated for socket.io v2 as well - 
https://github.com/ramkumarc/socket.io-mongodb-emitter

**Comment by MickL** [comment]
I got stuck here, too. I don't understand most of this adapter-logic so i can't make a pull request.

**Comment by amcdnl** [comment]
Simply updating the depedencies made it work, PR here - https://github.com/lklepner/socket.io-adapter-mongo/pull/3

**Comment by MickL** [comment]
The [Pull request](https://github.com/lklepner/socket.io-adapter-mongo/pull/4) is merged. So is this issue closed and fixed now?

**Comment by lklepner** [comment]
socket.io-adapter-mongo@2.0.0 has been published to NPM
